export const postData = [
  {
    id: 1,
    userId: 7,
    title: "Sunt Aut Facere Repellat Provident Occaecati Excepturi Optio Reprehenderit",
    body: "Molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto.",
  },
  {
    id: 2,
    userId: 4,
    title: "Qui Est Esse",
    body: "Est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis.",
  },
  {
    id: 3,
    userId: 7,
    title: "Ea Molestias Quasi Exercitationem Repellat Qui Ipsa Sit Aut",
    body: "Et iusto sed quo iure voluptatem occaecati omnis eligendi aut ad voluptatem doloribus vel accusantium quis pariatur molestiae porro eius odio et labore et velit aut.",
  },
  {
    id: 4,
    userId: 3,
    title: "Eum Et Est Occaecati",
    body: "Ullam et saepe reiciendis voluptatem adipisci sit amet autem assumenda provident rerum culpa quis hic commodi possimus sint velit.",
  },
  {
    id: 5,
    userId: 9,
    title: "Nesciunt Quas Odio",
    body: "Repudiandae veniam quaerat sunt sed alias aut fugiat et iusto sed et voluptates omnis voluptatem porro rerum.",
  },
  {
    id: 6,
    userId: 5,
    title: "Dolorem Eum Magni Eos Aperiam Quia",
    body: "Ut aspernatur corporis harum nihil quis provident sequi mollitia nobis aliquid molestiae perspiciatis et ea nemo asperiores.",
  },
  {
    id: 7,
    userId: 8,
    title: "Magnam Facilis Autem Dolorem",
    body: "Dolore placeat quibusdam ea quo vitae magni alias enim qui quis quo nemo aut saepe quidem repellat excepturi.",
  },
  {
    id: 8,
    userId: 2,
    title: "Dolorem Dolore Est Ipsam",
    body: "Dignissimos aperiam dolorem qui eum facilis quibusdam animi sint suscipit qui ipsa possimus cum quod molestiae.",
  },
  {
    id: 9,
    userId: 6,
    title: "Nesciunt Iure Omnis Dolorem Tempora Et Accusantium",
    body: "Consectetur animi nesciunt iure dolore enim quia ad veniam autem ut nostrum sed possimus.",
  },
  {
    id: 10,
    userId: 1,
    title: "Optio Molestias Id Quia Eum",
    body: "Quo et expedita modi cum officia vel magni doloribus qui repudiandae vero nisi quos veniam.",
  },
  {
    id: 11,
    userId: 4,
    title: "Et Ea Vero Quia Laudantium Autem",
    body: "Delectus reiciendis molestiae occaecati non minima eveniet qui voluptas voluptatibus itaque commodi.",
  },
  {
    id: 12,
    userId: 2,
    title: "In Quibusdam Tempore Odit Est Dolorem",
    body: "Beatae reprehenderit sunt optio ipsa et quia cupiditate quisquam nihil impedit occaecati qui voluptatem.",
  },
  {
    id: 13,
    userId: 5,
    title: "Dolorum Ut In Voluptas Mollitia Et Saepe Quo Animi",
    body: "Aut dicta possimus sint mollitia voluptas commodi quo deleniti esse sit tempora.",
  },
  {
    id: 14,
    userId: 8,
    title: "Voluptatem Eligendi Optio",
    body: "Fuga et accusamus dolorum perferendis illo voluptas non doloremque neque facere ad qui praesentium.",
  },
  {
    id: 15,
    userId: 9,
    title: "Eveniet Quod Temporibus",
    body: "Reprehenderit quos placeat vel minima ipsa dolores modi perspiciatis mollitia rem voluptatem.",
  },
];
